apiVersion: v1
kind: ConfigMap
metadata:
  name: monitoring-config
  namespace: infra
data:
  config.yaml: |
    tunnel: k8s-monitoring
    credentials-file: /etc/cloudflared/creds/credentials.json
    ingress:
      - hostname: grafana.your-domain.com
        service: http://monitoring-grafana.monitoring.svc.cluster.local:80
      - hostname: prom.your-domain.com
        service: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      - service: http_status:404
