apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqld-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sqld-frontend
  template:
    metadata:
      labels:
        app: sqld-frontend
    spec:
      containers:
        - name: sqld-frontend
          image: ghcr.io/beolle/sqld-frontend:sha-82a0816
          imagePullPolicy: Always
          ports:
            - containerPort: 80
