apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-grafana-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  local:
    path: /mnt/data/ronny-project/grafana-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - ronny
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-grafana-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  volumeName: monitoring-grafana-data-pv
  resources:
    requests:
      storage: 5Gi
