apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring-alerts
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/BeolLe/sqld_project_gitops
    targetRevision: main
    path: infra/cluster/monitoring/alerts
    kustomize: {}

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
