apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: front-k8s-updater
  namespace: argocd
spec:
  namespace: argocd

  commonUpdateSettings:
    updateStrategy: latest
    allowTags: regexp:^sha-

  applicationRefs:
    - namePattern: "front-k8s"
      writeBackConfig:
        method: "git:secret:argocd/ghcr-creds"
        gitConfig:
          branch: "main"
      images:
        - alias: frontend
          imageName: ghcr.io/beolle/sqld-frontend
