apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-airflow.yaml
  - argocd-front.yaml
  - argocd-back.yaml
  - argocd-sqld-internal.yaml
  - argocd-sqld-public.yaml
  - argocd-gateway.yaml
  - airflow-image-updater.yaml
  - back-k8s-updater.yaml
  - front-image-updater.yaml
  - argocd-image-updater-config.yaml
